DEB [20210829-22:29:00.656] thr=1   paramiko.transport: starting thread (client mode): 0xf5318c50L
INF [20210829-22:29:00.879] thr=1   paramiko.transport: Connected (version 2.0, client OpenSSH_7.2p2)
DEB [20210829-22:29:01.099] thr=1   paramiko.transport: kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
ERR [20210829-22:29:01.099] thr=1   paramiko.transport: Exception: Incompatible ssh peer (no acceptable kex algorithm)
ERR [20210829-22:29:01.100] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20210829-22:29:01.100] thr=1   paramiko.transport:   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1627, in run
ERR [20210829-22:29:01.100] thr=1   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20210829-22:29:01.100] thr=1   paramiko.transport:   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1717, in _negotiate_keys
ERR [20210829-22:29:01.100] thr=1   paramiko.transport:     self._parse_kex_init(m)
ERR [20210829-22:29:01.100] thr=1   paramiko.transport:   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1832, in _parse_kex_init
ERR [20210829-22:29:01.100] thr=1   paramiko.transport:     raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)')
ERR [20210829-22:29:01.100] thr=1   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable kex algorithm)
ERR [20210829-22:29:01.100] thr=1   paramiko.transport: 
DEB [20210829-22:29:09.265] thr=2   paramiko.transport: starting thread (client mode): 0xf508c490L
INF [20210829-22:29:09.488] thr=2   paramiko.transport: Connected (version 2.0, client OpenSSH_7.2p2)
DEB [20210829-22:29:09.708] thr=2   paramiko.transport: kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
ERR [20210829-22:29:09.709] thr=2   paramiko.transport: Exception: Incompatible ssh peer (no acceptable kex algorithm)
ERR [20210829-22:29:09.709] thr=2   paramiko.transport: Traceback (most recent call last):
ERR [20210829-22:29:09.709] thr=2   paramiko.transport:   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1627, in run
ERR [20210829-22:29:09.709] thr=2   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20210829-22:29:09.709] thr=2   paramiko.transport:   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1717, in _negotiate_keys
ERR [20210829-22:29:09.709] thr=2   paramiko.transport:     self._parse_kex_init(m)
ERR [20210829-22:29:09.709] thr=2   paramiko.transport:   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1832, in _parse_kex_init
ERR [20210829-22:29:09.709] thr=2   paramiko.transport:     raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)')
ERR [20210829-22:29:09.709] thr=2   paramiko.transport: SSHException: Incompatible ssh peer (no acceptable kex algorithm)
ERR [20210829-22:29:09.709] thr=2   paramiko.transport: 
